myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # 注意单引号，并指定namespace
    url(r'^blog/', include('simpleblog.urls', namespace='simpleblog')),
    url(r'^admin/', include(admin.site.urls)),
]

simpleblog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(regex, view, name)
    url(r'^$', views.blog_index, name='blog_index'),
    # article/2
    url(r'^article/(?P<article_id>\d+)/$', views.article_page, name='article_page'),
    url(r'^article/(?P<article_id>\d+)/edit/$', views.edit_page, name='edit_page'),
    url(r'^article/edit_action/$', views.edit_action, name='edit_action'),
]

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField('标题', max_length=200)
    content = models.TextField('内容', default='Blog Content')
    pub_time = models.DateTimeField('发表日期', auto_now=True)

    def __str__(self):
        return self.title

simpleblog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField('标题', max_length=200)
    content = models.TextField('内容', default='blog content')
    pub_date = models.DateTimeField('发表时间', auto_now=True)

    def __str__(self):
        return self.title

simpleblog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Article


def blog_index(request):
    # 获取所有Article
    articles = Article.objects.all()

    # render(request, template_name, context)
    # 注意：
    # context是字典dict
    # dict中key为字符串
    return render(request, template_name='simpleblog/index.html', context={'articles': articles})


# article_id对应urls中的参数
def article_page(request, article_id):
    article = Article.objects.get(id=article_id)
    return render(request, template_name='simpleblog/article_page.html', context={'article': article})


def edit_page(request, article_id):
    # article_id为0，新建博客, 注意char到int转换
    if int(article_id) == 0:
        return render(request, template_name='simpleblog/edit_page.html')
    else:
        # 编辑已有博客
        article = Article.objects.get(id=article_id)
        return render(request, template_name='simpleblog/edit_page.html', context={'article': article})


def edit_action(request):

    article_id = request.POST['article_id']
    new_title = request.POST['title']
    new_content = request.POST['content']
    # article_id为0，新建博客
    if int(article_id) == 0:
        new_article=Article.objects.create(title=new_title, content=new_content)
        return HttpResponseRedirect(reverse('simpleblog:article_page', args=(new_article.id, )))
    else:
        # 编辑已有博客
        article = Article.objects.get(id=article_id)
        article.title = new_title
        article.content = new_content
        article.save()
        # reverse(namespace:name, url参数列表)
        return HttpResponseRedirect(reverse('simpleblog:article_page', args=(article_id, )))

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>岳周's Blog</title>
</head>
<body>
<h1>
    {% for article in articles %}
        <a href="{%  url 'blog:article_page' article.id %}">{{ article.title }}</a>
        <br/><br/>
    {% endfor %}
</h1>
<h3>
    <a href="{% url 'blog:article_edit' 0 %}">新建文章</a>
</h3>
</body>
</html>

simpleblog/templates/simpleblog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ article.title }}</title>
</head>
<body>
<h1>
    {{ article.title }}
</h1>
<br/>
<h2>
    {{ article.content }}
</h2>
<br/><br/>
<h4>
    <a href="{% url 'simpleblog:edit_page' article.id %}">编辑此文章</a>
</h4>
</body>
</html>

simpleblog/templates/simpleblog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ article.title | default:"发表新文章"}}</title>
</head>
<body>
<form action="{% url 'simpleblog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id | default:0}}"/>
    <label>
        标题：
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/>
    <label>
        内容：
        <input type="text" name="content" value="{{ article.content }}"/>
    </label>
    <br/>
    <input type="submit" name="提交"/>
</form>
</body>
</html>

simpleblog/templates/simpleblog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>岳周's Blog</title>
</head>
<body>
<h1>
    {% for article in articles %}
        <a href="{% url 'simpleblog:article_page' article.id %}">{{ article.title }}</a>
        <br/>
    {% endfor %}
</h1>
<br/><br/>
<h3>
    <a href="{% url 'simpleblog:edit_page' 0 %}">发表博客</a>
</h3>
</body>
</html>